### ISSUE TITLE
Module not found: Error: Can't resolve '@brunoc/ngx-viacep'

### ISSUE THREAD

**Issue by yasminlopes** [brunoc107/ngx-viacep#116]
Eu atualizei o Angular para a versão 16.2.0 e também atualizei a biblioteca para a sua última versão disponível (3.3.8), e está dando esse problema.

Também criei um novo projeto utilizando as mesmas versões, porém, o erro persiste. Talvez a nova versão do Angular quebrou a lib?

**Comment by ganholete** [comment]
Estou com o mesmo problema.

**Comment by matheusjordan** [comment]
Estou com o mesmo problema, atualizei para a versão 3.3.8 e no meu projeto com Angular 14.3.0:

Error: Module not found: Error: Can't resolve '@brunoc/ngx-viacep'...

Estou utilizando o import abaixo:

`import {NgxViacepService} from "@brunoc/ngx-viacep";`

**Comment by matheusjordan** [comment]
✅ Consegui corrigir o problema fazendo um downgrade para a versão 3.3.7.

`yarn add @brunoc/ngx-viacep@3.3.7`

**Comment by brunoc107** [comment]
Pessoal, atualizei as referências presentes no package.json da lib. Quando puderem confirmem aqui se funcionou pls.

**Comment by brunoc107** [comment]
Problema corrigido. Fechando a issue.
