### ISSUE TITLE
Deixar explícito as possíveis mensagens de erro do ErroCep

### ISSUE THREAD

**Issue by Barbiero** [brunoc107/ngx-viacep#19]
Algo da seguinte forma(erro-cep.ts):

```typescript
enum ErroCepValues {
  CEP_NAO_ENCONTRADO,
  CEP_VAZIO,
  CEP_INVALIDO,
  CEP_MUITO_CURTO,
  CEP_MUITO_LONGO,
  ERRO_UF,
  ERRO_UF_MUITO_CURTA,
  ERRO_UF_MUITO_LONGA,
  ERRO_UF_NAO_EXISTE,
  ERRO_MUNICIPIO,
  ERRO_MUNICIPIO_MUITO_CURTO,
  ERRO_LOGRADOURO,
  ERRO_LOGRADOURO_MUITO_CURTO,
  ERRO_SERVIDOR
}

export class ErroCep extends Error {
  constructor( message: Extract<keyof typeof ErroCepValues, string> ) {
    super(message);
  }
}
```

Desta forma, ao tentar ler `erro.message`, o typescript mostrará os possíveis valores que podem ser retornados da biblioteca. Útil quando você quer transformar o erro em algo mais amigável para o usuário, mas não sabe quais as possibilidades.

Faria um PR mas não tenho experiencia com opensource e não consegui rodar os testes daqui de casa.

**Comment by brunoc107** [comment]
Ótima sugestão :)
Cheguei a pensar em algo assim tb. Devo colocar em Alpha nos próximos dias.
Obrigado por sugerir!

**Comment by brunoc107** [comment]
A alteração foi feita e está no branch develop. No pacote npm/yarn, é a tag 1.1.0-alpha.
