### ISSUE TITLE
Module not found: Error: Can't resolve 'brunoc-ngx-viacep' in 

### ISSUE THREAD

**Issue by penihel** [brunoc107/ngx-viacep#2]
Ao executar um "build --prod"

Acontece o seguinte erro:

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'brunoc-ngx-viacep' in 'D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\app'
resolve 'brunoc-ngx-viacep' in 'D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\app'
  Parsed request is a module
  using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./src/app)
    resolve as module
      looking for modules in D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src
        using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./src)
          using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./src/brunoc-ngx-viacep)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep.js doesn't exist
            as directory
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep doesn't exist
      D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\app\node_modules doesn't exist or is not a directory
      D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\node_modules doesn't exist or is not a directory
      D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\node_modules doesn't exist or is not a directory
      D:\Source\Repos\IgrejasNetRepository\src\node_modules doesn't exist or is not a directory
      D:\Source\Repos\IgrejasNetRepository\node_modules doesn't exist or is not a directory
      D:\Source\Repos\node_modules doesn't exist or is not a directory
      D:\Source\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules
        using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./node_modules)
          using description file: D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\package.json (relative path: ./node_modules/brunoc-ngx-viacep)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep.js doesn't exist
            as directory
              D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep doesn't exist
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep.ts]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep.js]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\brunoc-ngx-viacep]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\app\node_modules]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\src\node_modules]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\node_modules]
[D:\Source\Repos\IgrejasNetRepository\src\node_modules]
[D:\Source\Repos\IgrejasNetRepository\node_modules]
[D:\Source\Repos\node_modules]
[D:\Source\node_modules]
[D:\node_modules]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep.ts]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep.js]
[D:\Source\Repos\IgrejasNetRepository\src\IgrejasNet.Web.UserInterface\ClientApp\node_modules\brunoc-ngx-viacep]
 @ ./src/app/app.module.ngfactory.js 30:0-41
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by Shelps** [comment]
No meu, quando executo "ionic cordova build android --prod" acontece o seguinte erro.

Error: Metadata version mismatch for module /Users/shelps/Projetos/ionic/new-valelance/node_modules/@brunoc/ngx-viacep/brunoc-ngx-viacep.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler/bundles/compiler.umd.js:25748:34)
    at StaticSymbolResolver._createSymbolsOf (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler/bundles/compiler.umd.js:25536:46)
    at StaticSymbolResolver.getSymbolsOf (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler/bundles/compiler.umd.js:25517:14)
    at /Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler/bundles/compiler.umd.js:24376:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler/bundles/compiler.umd.js:24375:79)
    at AotCompiler.analyzeModulesAsync (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler/bundles/compiler.umd.js:23931:47)
    at CodeGenerator.codegen (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at Object.doCodegen (/Users/shelps/Projetos/ionic/new-valelance/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:51)

**Comment by penihel** [comment]
Eu contornei o problema, "copiando" para dentro do meu projeto o código do 
https://github.com/brunoc107/ngx-viacep/blob/master/src/viacep.service.ts

Com isso deixei de utiliza-lo como pacote npm, e agora faz parte do meu projeto, até melhorei alguns pontos.

**Comment by brunoc107** [comment]
Oi, pessoal
Atualmente está meio complicado atualizar a biblioteca. Pretendo atualizá-la e corrigir estes bugs, mas de imediato vai ficar difícil. @penihel, que bom que conseguiu contornar o problema. Aparentemente, as últimas atualizações do framework quebraram a lib.

**Comment by brunoc107** [comment]
Problemas resolvidos. Com a refatoração feita, algumas coisas na interface publica mudaram. As mudanças estão documentadas no README. São poucas mudanças e pretendo manter esta interface o mais estável possível.
