### ISSUE TITLE
Cannot find name 'Extract'

### ISSUE THREAD

**Issue by ioxua-os** [brunoc107/ngx-viacep#23]
Por algum motivo, usando `Angular CLI v 6.0.8` e `Angular 5.2.11`, compilar um projeto com NgxViacep como dependência resulta em: 
`ERROR in node_modules/@brunoc/ngx-viacep/lib/model/erro-cep.d.ts(18,26): error TS2304: Cannot find name 'Extract'.`
Ao que parece, o erro está nas definições do arquivo `erro-cep.ts`: `erro-cep.d.ts`, porém não consegui solucionar até agora :/

**Comment by brunoc107** [comment]
Por favor, verifique a versão do typescript no seu projeto, a versão mínima do typescript necessária para a lib é a 2.9.2

**Comment by ioxua-os** [comment]
No final das contas era isso mesmo. Muito obrigado!
