### ISSUE TITLE
Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by diegoserrat** [brunoc107/ngx-viacep#3]
Boa tarde!

Eu estava usando o ngx-via cep no angular 5 com http e estava funcionando. E agora eu estou mudando o http para o httpClient e começou a gerar esse erro no CORS. Pelo o que andei lendo pode ser algo na parte do backend. 

É isso, ou seria algo do meu lado?

Obrigado!

**Comment by brunoc107** [comment]
Boa trade, Diego

Aparentemente este é um erro no backend, pois o mesmo deveria enviar o header para autorizar o browser fazer a requisição para o domínio do viacep. A lib tb está desatualizada, tenho que fazer um patch para isso, mas ando muito ocupado ultimamente, e como mantenho este repo no tempo vago, pode ser que demore mais um pouco.

**Comment by brunoc107** [comment]
Problemas resolvidos. Com a refatoração feita, algumas coisas na interface publica mudaram. As mudanças estão documentadas no README. São poucas mudanças e pretendo manter esta interface o mais estável possível.

**Comment by Hawkinks** [comment]
Olá!
Estou usando a última versão do ngx-viacep com angular 6, e está acontecendo o mesmo que o autor do tópico relatou.
Alguém saberia me auxiliar?

Abraços!

**Comment by brunoc107** [comment]
Oi, @Hawkinks 
Poderia colocar o código onde o erro está acontecendo? 
Assim teria mais contexto.
Abraço.

**Comment by brunoc107** [comment]
Oi, @Hawkinks 

Poderia fornecer o seu package.json e o código onde vc faz a chamada que origina o erro?
Assim haveria mais contexto para resolver o problema.

Abraço!

**Comment by brunoc107** [comment]
@Hawkinks
Criei um projeto para testar aqui e não consegui reproduzir o erro.

Aqui funcionou normalmente. Será que não é outra chamada que está quebrando?

Este erro acontecia quando o servidor do viacep retornava status 400 (bad request) e foi tratado na lib fazendo a validação antes de disparar para o serviço, como sugerido na página do viacep:

> Quando consultado um CEP de formato inválido, por exemplo: "950100100" (9 dígitos), "95010A10" (alfanumérico), "95010 10" (espaço), o código de retorno da consulta será um 400 (Bad Request). Antes de acessar o webservice, valide o formato do CEP e certifique-se que o mesmo possua {8} dígitos

**Comment by Hawkinks** [comment]
@brunoc107
Perdão por ter tomado o seu tempo. Acabei descobrindo que o problema é no JwtInterceptor que uso no projeto. Vacilo meu. -.-'

Sem você eu não teria descoberto.
Muito obrigado!

**Comment by brunoc107** [comment]
Que bom que encontrou a solução :)
Fou fechar a issue.
