### ISSUE TITLE
Access to XMLHttpRequest at 'https://viacep.com.br/ws/03077100/json' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by emysmoura** [brunoc107/ngx-viacep#45]
Boa tarde!

Estou usando o nx-viacep no angular 7, e o seguinte erro aparece: 

"Access to XMLHttpRequest at 'https://viacep.com.br/ws/03077100/json' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.".

Verifiquei outro issue com o erro igual, porém a solução não me atendeu.
Coloquei um valor fixo de cep para teste, um que já foi verificado no via cep e realmente existe, verifiquei se está sendo enviada a quantidade certa de caracteres(8) e tudo está dentro dos conformes, mas mesmo assim o erro aparece.

Pode me ajudar?

**Comment by woj1965** [comment]
Também estou com o mesmo problema.

**Comment by brunoc107** [comment]
Pessoal, desculpem a demora para responder, mas ultimamente está tudo uma correria insana.
Este fim de semana vou revisar a lib para rastrear o erro. Se tiverem as stack traces para postarem aqui, seria legal tb.
Até breve!

**Comment by brunoc107** [comment]
Pessoal, bom dia.
Aparentemente, algum middleware de autenticação de está adicionando o header "authorization" em todas as chamadas http. O erro é por que a chamada de pre-flight (Método HTTP OPTIONS) para a rota https://viacep.com.br/ws/03077100/json está sendo feita com o header authorization.
Meu conselho é que somente adicionem o header nas rotas da sua aplicação, deixando as demais rotas inalteradas.

**Comment by osnjunior91** [comment]
Boa tarde, estava tendo o mesmo problema, acertei tirando a ultima barra, no final da strin, Ex: 

``this.http.get<any>(`https://viacep.com.br/ws/${CEP}/json`)`

**Comment by MagicLamp01** [comment]
> get(cep: any) {
> return new Observable((x)=>{
> var request = new XMLHttpRequest();
> request.open('get', `https://viacep.com.br/ws/${cep}/json/`, true);
> request.send();
> request.onload = function () {
> var data = JSON.parse(this.response);
> x.next(data)
> }
> })
> }

Esta solução resolveu meu problema.
