### ISSUE TITLE
this library still maintained?

### ISSUE THREAD

**Issue by maykon-oliveira** [brunoc107/ngx-viacep#59]

**Comment by brunoc107** [comment]
Oi, @maykon-oliveira
Já não a atualizo há algum tempo. Não tenho tido muito tempo livre, então por enquanto estou revisando PRs, mas não estou escrevendo/refatorando código.

**Comment by brunoc107** [comment]
Valeu pelo Pull Request, Maykon. Já foi feito o merge!
