### ISSUE TITLE
Cannot find module '@brunoc/ngx-viacep' or its corresponding type declarations.

### ISSUE THREAD

**Issue by maykon-oliveira** [brunoc107/ngx-viacep#78]
Cara, não sei o por que ainda, mas eu tentei atualizar a lib em um projeto e ta dando esse problema `Cannot find module '@brunoc/ngx-viacep' or its corresponding type declarations.`. Eu criei um novo projeto angular do 0 e instalei a lib e esta acontecendo a mesma coisa.

No showcase do próprio projeto ele resolve o arquivo de tipos, mas em projeto novo ele ta dando erro, vou dar uma olhada o que pode ser, talvez seja no build.

**Comment by brunoc107** [comment]
A importação está muito estranha mesmo:
`Error: ./src/app/app.module.ts
Module not found: Error: Can't resolve '@brunoc/ngx-viacep/brunoc-ngx-viacep' in '/home/bruno/Dev/testes/src/app'

Error: ./src/app/app.component.ts
Module not found: Error: Can't resolve '@brunoc/ngx-viacep/brunoc-ngx-viacep' in '/home/bruno/Dev/testes/src/app'`

**Comment by maykon-oliveira** [comment]
Essa essa versão 3.0.2 ainda não resolveu o problema. Cabuloso esse bug, se instalar em outro projeto com npm link funciona.

**Comment by Hawkinks** [comment]
Alguma solução?

**Comment by OllieStudio** [comment]
Olá, estou com o mesmo problema.

**Comment by maykon-oliveira** [comment]
@brunoc107 essa última versão não foi pra produção.

**Comment by brunoc107** [comment]
@maykon-oliveira Preciso revisar o pipeline. Farei isso ainda essa semana.

**Comment by brunoc107** [comment]
@maykon-oliveira, Creio ter conseguido resolver o problema. No final, o package.json da lib (o que vai para o build) precisava especificar os entrypoints para cada formato de modulo e o arquivo de typings.

**Comment by yasminlopes** [comment]
estou enfrentando o mesmo problema na versão 3.3.8, usando angular v16

**Comment by Hudsonjr90** [comment]
@brunoc107 estou com um projeto de angular 14 que tinha a lib funcionando de boa, porém nenhuma outra versão, dá compatibilidade com angular15 em diante, pois estou atualizando a versão do angular desse projeto e está travando justamente nessa lib do cep.

**Comment by maykon-oliveira** [comment]
Aconselho abrir uma issue @Hudsonjr90 , mas achei uma issue falando que da suporte ao angular 15 já.

**Comment by OllieStudio** [comment]
Tenho usado mesmo no Angular 17, usando a opção --legacy-peer-deps ao instalar.
________________________________
De: Maykon Oliveira ***@***.***>
Enviado: quinta-feira, 11 de janeiro de 2024 10:18
Para: brunoc107/ngx-viacep ***@***.***>
Cc: OllieStudio ***@***.***>; Comment ***@***.***>
Assunto: Re: [brunoc107/ngx-viacep] Cannot find module ***@***.***/ngx-viacep' or its corresponding type declarations. (#78)


Aconselho abrir uma issue @Hudsonjr90<https://github.com/Hudsonjr90> , mas achei uma issue falando que da suporte ao angular 15 já.

**Comment by Hudsonjr90** [comment]
fiz isso @maykon-oliveira , valeu.

**Comment by Hudsonjr90** [comment]
@OllieStudio sim, porém um dos requisitos do projeto é rodar as coisas sem --force ou --legacy-peer-deps, pois mesmo com esses comandos a biblioteca não funciona 100%

**Comment by maykon-oliveira** [comment]
Não acho interessante precisar passar essas flags. Com a issue aberta, quem tiver disponibilidade vai dá uma olhadinha, se eu tiver um tempinho livre eu olho.
